spotify-downloader:
  avconv: false
  download-only-metadata: false
  dry-run: false
  file-format: '{track_name} - {artist}'
  folder: /data/data/com.termux/files/home/storage/shared/Termux/Spotify
  input-ext: .m4a
  log-level: INFO
  manual: false
  music-videos-only: false
  no-fallback-metadata: false
  no-metadata: false
  no-remove-original: false
  no-spaces: false
  output-ext: .mp3
  overwrite: prompt
  search-format: '{artist} - {track_name} lyrics'
  skip: null
  spotify_client_id: 4fe3fecfe5334023a1472516cc99d805
  spotify_client_secret: 0f02b7c483c04257984695007a4a8d5c
  trim-silence: false
  write-successful: null
  write-to: null
  youtube-api-key: null
